services:
  app:
    image: test:dev
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://mongodb/test_db

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - volum_db:/data/db/

volumes:
  volum_db:
    